### ISSUE TITLE
Link gives 404

### ISSUE THREAD

**Issue by vasarhelyia** [Skyscanner/Dixie#8]
http://skyscanner.github.io/Dixie/

**Comment by WiesnerPeti** [comment]
Hi @vasarhelyia,

thank you for reporting! We will check this out!

Cheers,
Peter

**Comment by WiesnerPeti** [comment]
Hi @vasarhelyia,

It is solved, now! :)

Thank you,
Peter

**Comment by vasarhelyia** [comment]
great, thanks! :+1: :blush:
